function deepFreeze(value) {
  for (const child of Object.values(value)) {
    if (child && typeof child === "object") deepFreeze(child);
  }
  return Object.freeze(value);
}

export const SMALLPEN_FORMAT_CAPABILITIES = deepFreeze({
  canonicalPackage: {
    entryKinds: [
      "assets",
      "components",
      "contexts",
      "requirements",
      "scenarios",
      "screens",
      "tokens",
    ],
    nodeTypes: [
      "COMPONENT",
      "COMPONENT_SET",
      "ELLIPSE",
      "FRAME",
      "GROUP",
      "IMAGE",
      "INSTANCE",
      "PATH",
      "RECTANGLE",
      "TEXT",
    ],
    assetLibraryModel: "local-colors-fonts-typographies-media",
    binaryBlobModel: "sha256-addressed",
    customFontModel: "families-variants-woff",
    componentCanonicalModel: "component-sets-sparse-variants",
    dependencyModel:
      "one-foundation-plus-multiple-local-or-url-library-sources",
    contextModel: "finite-axes-defaults-profiles",
    effectiveTokenResolution:
      "product-first-specificity-then-foundation-fallback",
    fontImportConversion: "sfnt-to-woff",
    fontImportTypes: ["font/otf", "font/ttf", "font/woff"],
    repairChoices: [
      "choose-foundation",
      "recreate-product-asset",
      "remove-dependent-usage",
      "retarget-reference",
    ],
    presentationRootForms: ["legacy-single", "forest"],
    requirementModel: "requirements-links-flows-annotations",
    textModel: "blocks-runs",
    scenarioModel: "finite-declarative-actions",
    screenModel: "base-plus-independent-presentations",
    tokenCanonicalModel: "dtcg-smallpen-extension",
    tokenBindingFields: [
      "cornerRadius",
      "shadow",
      "blur",
      "backgroundBlur",
      "fill",
      "fills.N",
      "fontFamily",
      "fontSize",
      "fontWeight",
      "height",
      "itemSpacing",
      "opacity",
      "paddingBottom",
      "paddingLeft",
      "paddingRight",
      "paddingTop",
      "strokeWidth",
      "typography",
      "width",
    ],
    tokenLibraryModel: "ordered-sets-themes",
    tokenTypes: [
      "boolean",
      "border-radius",
      "color",
      "dimensions",
      "font-family",
      "font-size",
      "font-weight",
      "letter-spacing",
      "number",
      "opacity",
      "other",
      "rotation",
      "shadow",
      "sizing",
      "spacing",
      "string",
      "stroke-width",
      "text-case",
      "text-decoration",
      "typography",
    ],
  },
  canonicalWrite: {
    nodeFields: [
      "appliedTokens",
      "cornerRadius",
      "shadow",
      "blur",
      "backgroundBlur",
      "blend-mode",
      "fills",
      "layout",
      "layout-flex-dir",
      "layout-gap-type",
      "layout-gap",
      "layout-align-items",
      "layout-justify-content",
      "layout-align-content",
      "layout-wrap-type",
      "layout-padding-type",
      "layout-padding",
      "layout-item-margin",
      "layout-item-margin-type",
      "layout-item-h-sizing",
      "layout-item-v-sizing",
      "layout-item-max-h",
      "layout-item-min-h",
      "layout-item-max-w",
      "layout-item-min-w",
      "layout-item-align-self",
      "layout-item-absolute",
      "layout-item-z-index",
      "constraints-h",
      "constraints-v",
      "fixed-scroll",
      "exports",
      "content",
      "pathData",
      "points",
      "flipX",
      "flipY",
      "growType",
      "grids",
      "height",
      "hide-fill-on-export",
      "hide-in-viewer",
      "interactions",
      "locked",
      "masked-group",
      "mediaRef",
      "name",
      "opacity",
      "proportionLock",
      "rotation",
      "strokes",
      "show-content",
      "text",
      "textBlocks",
      "textStyle",
      "tokenBindings",
      "touched",
      "visible",
      "width",
      "x",
      "y",
    ],
    operationTypes: [
      "add-component",
      "add-presentation",
      "add-presentation-node",
      "clear-token-binding",
      "delete-component-set",
      "delete-context-file",
      "delete-interaction",
      "delete-requirement-file",
      "delete-scenario",
      "delete-screen",
      "delete-variant",
      "deprecate-token",
      "delete-presentation",
      "delete-presentation-node",
      "delete-component",
      "move-presentation",
      "move-presentation-nodes",
      "put-component-set",
      "put-context-file",
      "put-interaction",
      "put-library",
      "put-requirement-file",
      "put-scenario",
      "put-screen",
      "put-token",
      "put-variant",
      "remove-token",
      "remove-library",
      "repair-reference",
      "reorder-presentation-children",
      "replace-asset-library",
      "replace-token-library",
      "restore-canonical-entry",
      "select-instance-variant",
      "set-default-screen",
      "set-foundation-dependency",
      "set-active-token-themes",
      "set-token-binding",
      "set-token-value",
      "update-component-node",
      "update-node",
      "update-presentation",
      "update-presentation-node",
      "update-component",
    ],
  },
  penpotWrite: {
    attributes: [
      "applied-tokens",
      "background-blur",
      "blend-mode",
      "blur",
      "blocked",
      "fills",
      "flip-x",
      "flip-y",
      "grow-type",
      "grids",
      "height",
      "hide-fill-on-export",
      "hide-in-viewer",
      "interactions",
      "layout",
      "layout-flex-dir",
      "layout-gap-type",
      "layout-gap",
      "layout-align-items",
      "layout-justify-content",
      "layout-align-content",
      "layout-wrap-type",
      "layout-padding-type",
      "layout-padding",
      "layout-item-margin",
      "layout-item-margin-type",
      "layout-item-h-sizing",
      "layout-item-v-sizing",
      "layout-item-max-h",
      "layout-item-min-h",
      "layout-item-max-w",
      "layout-item-min-w",
      "layout-item-align-self",
      "layout-item-absolute",
      "layout-item-z-index",
      "constraints-h",
      "constraints-v",
      "fixed-scroll",
      "exports",
      "pathData",
      "hidden",
      "masked-group",
      "metadata",
      "name",
      "opacity",
      "proportion-lock",
      "r1",
      "r2",
      "r3",
      "r4",
      "rotation",
      "shadow",
      "show-content",
      "width",
      "x",
      "y",
      "content",
      "strokes",
      "touched",
    ],
    changeTypes: [
      "add-color",
      "add-component",
      "add-media",
      "add-page",
      "add-obj",
      "del-page",
      "del-obj",
      "del-component",
      "del-color",
      "del-media",
      "mod-page",
      "mod-obj",
      "mod-component",
      "mod-color",
      "mod-media",
      "mov-page",
      "mov-objects",
      "reg-objects",
      "reorder-children",
      "rename-token-set-group",
      "move-token-set",
      "move-token-set-group",
      "set-active-token-themes",
      "set-flow",
      "set-tokens-status",
      "set-token",
      "set-token-set",
      "set-token-theme",
      "add-typography",
      "mod-typography",
      "del-typography",
    ],
    derivedAttributes: [
      "points",
      "position-data",
      "proportion",
      "selrect",
      "transform",
      "transform-inverse",
    ],
    operationTypes: ["set", "set-touched"],
    pageAttributes: [
      "background",
      "name",
      "pixel-grid-color",
      "pixel-grid-opacity",
    ],
    presentationMoveScope: "within-screen",
    presentationTarget: "default-screen",
    componentDeletePolicy: "unused-only",
    assetDeletePolicy: "unused-only",
  },
  version: 1,
  webProjection: {
    appliedTokenAttributes: [
      "column-gap",
      "fill",
      "font-family",
      "font-size",
      "font-weight",
      "height",
      "layout-item-max-h",
      "layout-item-max-w",
      "layout-item-min-h",
      "layout-item-min-w",
      "letter-spacing",
      "line-height",
      "m1",
      "m2",
      "m3",
      "m4",
      "opacity",
      "p1",
      "p2",
      "p3",
      "p4",
      "r1",
      "r2",
      "r3",
      "r4",
      "rotation",
      "row-gap",
      "shadow",
      "stroke-color",
      "stroke-width",
      "text-case",
      "text-decoration",
      "typography",
      "width",
    ],
    cornerRadiusForms: ["uniform", "per-corner"],
    componentModel: "located-main-instance",
    entryKinds: ["assets", "components", "screens", "tokens"],
    fillTypes: ["image", "linear-gradient", "radial-gradient", "solid"],
    localAssetTypes: ["color", "font", "media", "typography"],
    nodeFields: [
      "appliedTokens",
      "backgroundBlur",
      "blend-mode",
      "blur",
      "children",
      "componentId",
      "componentVariantId",
      "cornerRadius",
      "fills",
      "flipX",
      "flipY",
      "growType",
      "grids",
      "height",
      "hide-fill-on-export",
      "hide-in-viewer",
      "id",
      "interactions",
      "layout",
      "layout-flex-dir",
      "layout-gap-type",
      "layout-gap",
      "layout-align-items",
      "layout-justify-content",
      "layout-align-content",
      "layout-wrap-type",
      "layout-padding-type",
      "layout-padding",
      "layout-item-margin",
      "layout-item-margin-type",
      "layout-item-h-sizing",
      "layout-item-v-sizing",
      "layout-item-max-h",
      "layout-item-min-h",
      "layout-item-max-w",
      "layout-item-min-w",
      "layout-item-align-self",
      "layout-item-absolute",
      "layout-item-z-index",
      "constraints-h",
      "constraints-v",
      "fixed-scroll",
      "exports",
      "content",
      "pathData",
      "points",
      "locked",
      "masked-group",
      "mediaRef",
      "name",
      "opacity",
      "proportionLock",
      "rotation",
      "sourceNodeId",
      "strokes",
      "shadow",
      "show-content",
      "text",
      "textBlocks",
      "textStyle",
      "touched",
      "type",
      "visible",
      "width",
      "x",
      "y",
    ],
    nodeTypes: [
      "COMPONENT",
      "ELLIPSE",
      "FRAME",
      "GROUP",
      "IMAGE",
      "INSTANCE",
      "PATH",
      "RECTANGLE",
      "TEXT",
    ],
    presentationRootForms: ["legacy-single", "forest"],
    textModel: "blocks-runs",
    strokeTypes: ["image", "linear-gradient", "radial-gradient", "solid"],
    supportedMediaTypes: [
      "image/gif",
      "image/jpeg",
      "image/png",
      "image/svg+xml",
      "image/webp",
    ],
    supportedFontTypes: ["font/otf", "font/ttf", "font/woff", "font/woff2"],
    assetLibraryEntries: "zero-or-one",
    tokenLibraryEntries: "zero-or-one",
    touchedGroups: [
      "blur-group",
      "constraints-group",
      "content-group",
      "fill-group",
      "geometry-group",
      "layer-effects-group",
      "mask-group",
      "modifiable-group",
      "name-group",
      "radius-group",
      "shadow-group",
      "stroke-group",
      "text-display-group",
      "text-font-group",
      "visibility-group",
    ],
  },
});

export const SMALLPEN_RUNTIME_CAPABILITIES = deepFreeze({
  agentExecution: false,
  aiChat: false,
  comments: false,
  externalChanges: true,
  localHistory: true,
  mcp: false,
  multiplePackages: true,
  networkInfrastructure: false,
  plugins: false,
  presence: false,
  realtimeCollaboration: false,
  remoteHistory: false,
  repositoryMerge: false,
  reviewWorkflow: false,
});
