#!/usr/bin/env node

import { execFile } from "node:child_process";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { randomUUID } from "node:crypto";
import { CLI_RULES } from "../apps/cli/bin/workflow.mjs";
import { commandContract } from "../apps/cli/bin/command-contract.mjs";
import {
  OUTPUT_LIMIT_BYTES,
  RESULT_RETENTION_MS,
} from "../apps/cli/bin/result-files.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const scenes = [
  {
    name: "smallpen-ui-design",
    source: "ui-design.md",
    description:
      "Design application interfaces and prototypes in SmallPen. Clarify requirements, build shared Tokens and components, adapt platforms through reuse, and verify explicit combinations. Deliver design artifacts; use for application UI design rather than production code or character/animation materials.",
  },
];

export async function buildSkills({
  output = join(root, "skills"),
  check = false,
} = {}) {
  const { stdout } = await promisify(execFile)(process.execPath, [
    join(root, "apps", "cli", "bin", "smallpen.mjs"),
    "schema",
    "command",
    "project",
    "init",
    "--json",
    "--stdout",
  ]);
  const { cliVersion, contractRevision } = JSON.parse(stdout);
  const template = (
    await readFile(join(root, "skill-src", "base.md"), "utf8")
  ).trim();
  const common =
    `${template}\n\n## CLI rules from source\n\n` +
    [
      `CLI version: ${cliVersion}. Use the installed CLI's help/schema when its version differs.`,
      `Replies are compact JSON with a ${OUTPUT_LIMIT_BYTES / 1024} KiB budget. Large complete results use resultFile paths; --full expands data, while --stdout explicitly requests large stdout.`,
      `Temporary results have unique names in one system temporary directory. Each invocation cleans managed files older than ${RESULT_RETENTION_MS / 60000} minutes. Read them promptly; --output keeps requested deliverables.`,
      `When the project uses Tokens: ${CLI_RULES.selection.defaults}`,
      CLI_RULES.selection.precedence,
      CLI_RULES.selection.dimensions,
      CLI_RULES.selection.writes,
      `Scoped checks: ${commandContract("validate").purpose}.`,
    ]
      .map((line) => `- ${line}`)
      .join("\n");
  const stale = [];
  for (const scene of scenes) {
    const body = (
      await readFile(join(root, "skill-src", scene.source), "utf8")
    ).trim();
    const content = [
      "---",
      `name: ${scene.name}`,
      `description: ${JSON.stringify(scene.description)}`,
      "metadata:",
      `  cli-version: ${JSON.stringify(cliVersion)}`,
      `  cli-contract-revision: ${JSON.stringify(contractRevision)}`,
      "---",
      "",
      "<!-- Generated by npm run build:skills. Edit skill-src, not this file. -->",
      "",
      common,
      "",
      body,
      "",
    ].join("\n");
    const target = join(resolve(output), scene.name, "SKILL.md");
    if (check) {
      let actual;
      try {
        actual = await readFile(target, "utf8");
      } catch (error) {
        if (error.code !== "ENOENT") throw error;
      }
      if (actual !== content) stale.push(target);
      continue;
    }
    await mkdir(dirname(target), { recursive: true });
    const temporary = `${target}.${randomUUID()}.tmp`;
    try {
      await writeFile(temporary, content, "utf8");
      await rename(temporary, target);
    } finally {
      await rm(temporary, { force: true });
    }
  }
  if (stale.length)
    throw new Error(
      `Stale generated Skills; run npm run build:skills:\n${stale.join("\n")}`,
    );
  return {
    status: check ? "current" : "built",
    output: resolve(output),
    skills: scenes.map(({ name }) => name),
  };
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const args = process.argv.slice(2);
  const options = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--check") options.check = true;
    else if (
      args[i] === "--output" &&
      args[i + 1] &&
      !args[i + 1].startsWith("--")
    )
      options.output = args[++i];
    else throw new Error(`Unknown or incomplete option: ${args[i]}`);
  }
  buildSkills(options)
    .then((result) => process.stdout.write(`${JSON.stringify(result)}\n`))
    .catch((error) => {
      process.stderr.write(`${error.message}\n`);
      process.exitCode = 1;
    });
}
